<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('transactions', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('internal_reference')->unique();  // Generated by the app
            $table->string('external_reference')->nullable(); // From external request
            $table->string('processor_reference')->nullable(); // From payment processor
            
            $table->enum('transaction_type', [
                'deposit',
                'withdrawal',
                'transfer',
                'charge',
                'reversal',
                'lien',
                'lien_release'
            ]);
            
            $table->enum('processing_type', ['intra', 'inter']);
            $table->string('processing_channel'); // e.g., 'web', 'mobile', 'api', 'batch'
            
            $table->uuid('source_account_id');
            $table->uuid('destination_account_id')->nullable();
            $table->string('currency', 3);
            $table->decimal('amount', 19, 4);
            
            // Balance snapshots before transaction
            $table->decimal('source_ledger_balance_before', 19, 4);
            $table->decimal('source_locked_balance_before', 19, 4);
            $table->decimal('source_available_balance_before', 19, 4);
            
            // Balance snapshots after transaction
            $table->decimal('source_ledger_balance_after', 19, 4);
            $table->decimal('source_locked_balance_after', 19, 4);
            $table->decimal('source_available_balance_after', 19, 4);
            
            $table->enum('status', ['pending', 'processing', 'completed', 'failed', 'reversed','awaiting_compliance'])->default('pending');
            $table->text('description')->nullable();
            $table->json('metadata')->nullable(); // For additional transaction details
            
            // For reversals
            $table->uuid('original_transaction_id')->nullable();
            $table->foreign('original_transaction_id')->references('id')->on('transactions');
            
            // Account relationships
            $table->foreign('source_account_id')->references('id')->on('accounts');
            $table->foreign('destination_account_id')->references('id')->on('accounts');
            
            $table->uuid('created_by_user_id');
            $table->uuid('approved_by_user_id')->nullable();
            $table->timestamp('approved_at')->nullable();
            
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down()
    {
        Schema::dropIfExists('transactions');
    }
};